### PR TITLE
Activate strict typing in Explorer for Endevor

### PR DESCRIPTION
**Pull request by katelynienaber**
Strict typing should be enabled in Explorer for Endevor. So in this PR, the `strict` option for compilation has been turned on, and all related errors have been fixed.

Changelog: Activated strict typing in the Typescript compiler options

### CODE REVIEW

**Comment by katelynienaber** [comment]
Addresses this issue (but in E4E): https://github.com/zowe/vscode-extension-for-zowe/issues/852

**Comment by Alexandru-Dumitru** [comment]
Please open against `development` branch. Also commit message doesn't follow https://www.conventionalcommits.org/en/v1.0.0-beta.2/ as it's mentioned in the checklist.

**Comment by katelynienaber** [comment]
> Please open against `development` branch. Also please remove the commit message template, as we don't have this set up here.

Done ^^

**Review by Alexandru-Dumitru — APPROVED** [review]
Tested manually and runs ok. Thanks for doing it.

**Pull request merged**
