### PR TITLE
Fix Issue 42: Loads the connection that is found in settings.json

### PR DESCRIPTION
**Pull request by jellypuno**
Added changes for this PR:
- Settings update are added in the Global Configuration
- Call for addSesssion is also added in loadRepositories()
- Add the logs folder in .gitignore

Signed-off-by: Jessielaine Punongbayan <jessielaine.punongbayan@broadcom.com>

### CODE REVIEW

**Comment by jellypuno** [comment]
Hi @Alexandru-Dumitru @zdmullen , Kindly review my PR. Thank you! 😊

**Comment by zdmullen** [comment]
So I've just tested it. One thing that I've found, and perhaps this is worth investigating further, is that if I add a profile from the dropdown (one I've already created from CLI) but I do not choose an Endevor instance, it will not re-appear in the tree upon a reload. I was wondering if we could somehow keep even an invalid profile, or one that does not have an Endevor instance associated with it, in the tree...

**Comment by zdmullen** [comment]
If you could make it so that profiles remain in the tree, even when a host has not been added in a session, that would be great (as we discussed). Thanks.

**Comment by jellypuno** [comment]
@zdmullen I could do that. There is still an issue with persistence of the hosts but I think it could be handled in a different issue.

**Review by Alexandru-Dumitru — COMMENTED** [review]
I have noticed the same thing. 
In `EndevorController` i can see that `let connNode = EndevorController.instance.findNodeByConnectionName(connName);` fails to get the second one. `connName` is there from settings, but is not found in the `this._rootNode.children`. (Line 202, same file).

Another thing to mention (maybe in release notes) is that since we changed the target settings file to global, users need to delete any remnants from workspace settings.

Need to investigate more about the rootNode not having more connections at startup.

**Comment by jellypuno** [comment]
> In EndevorController i can see that let connNode = EndevorController.instance.findNodeByConnectionName(connName); fails to get the second one. connName is there from settings, but is not found in the this._rootNode.children. (Line 202, same file).

I saw this before that is why I changed to Global settings. When VSCode uses get() it only gets the Global settings and not the workspace settings. I investigated it but there was no API to get from workspace. No idea why.

But since we wanted to persist the data, I thought it is a good idea to just switch to global settings so that I can keep my settings whenever I create a new workspace.

**Review by zdmullen — APPROVED** [review]
LGTM

**Pull request merged**
