### PR TITLE
Fix listing of instances

### PR DESCRIPTION
**Pull request by VitGottwald**
Signed-off-by: Vit Gottwald <vit.gottwald@broadcom.com>

### CODE REVIEW

**Comment by katelynienaber** [comment]
I am getting this error when I try to run the extension:
image

**Comment by katelynienaber** [comment]
Also it's not working for this Endevor profile, with ru set to either true or false:
host: ca31.lvn.broadcom.net
port: 47400
protocol: https
basePath: /EndevorService/api/v2/
user: xxxxx
password: xxxxx
rejectUnauthorized: false

It works on this one with ru = true/false though:
host: tso1.lvn.broadcom.net
port: 50004
protocol: http
user: xxxxx
password: xxxxx
rejectUnauthorized: false

**Comment by katelynienaber** [comment]
Also it's not working for Endevor profiles with ru set to either true or false, and protocol https.

Endevor profiles with http work either way though.

Someone lmk if they need to see the full profile, as Zach pointed out I can't post it here.

**Comment by nickImbirev** [comment]
> Also it's not working for Endevor profiles with ru set to either true or false, and protocol https.
> 
> Endevor profiles with http work with any ru though.
> 
> Someone lmk if they need to see the full profile, as Zach pointed out I can't post it here.

Soo, it works for me, but I cannot test it with unauthorized certificates. Maybe you can provide some output details?

**Comment by nickImbirev** [comment]
> I am getting this error when I try to run the extension:
> image

It seems like you have settings defined incorrectly. Can I ask you to reveal the output details? There should be some errors or smt like this. Or, if you tested this in debug mode - there should be some error messages in debug console.

**Review by nickImbirev — APPROVED** [review]
It works for me, but I did not have time to test it with self assigned certificates...

**Comment by katelynienaber** [comment]
@nickImbirev There's no errors in the log for the one I took a screenshot of. I checked both consoles. But the extension still runs.

I'm able to use it on HTTPS today. I'm not sure what was the deal with that profile not working at my house. But now it seems fine.

**Comment by nickImbirev** [comment]
> @nickImbirev There's no errors in the log for the one I took a screenshot of. I checked both consoles. But I still receive the error now. The extension starts successfully, so it's not a big deal. But I don't get this error on internal master.
> 
> I'm able to use it on HTTPS today. I'm not sure what was the deal with that profile not working at my house. But now it seems fine.

Are you sure, that you are testing the right branch in Vit's fork? I can only reproduce this startup error behaviour in E4E from Vit's outdated master branch. I think, the problem is about settings migration.

**Comment by nickImbirev** [comment]
> @nickImbirev There's no errors in the log for the one I took a screenshot of. I checked both consoles. But I still receive the error now. The extension starts successfully, so it's not a big deal. But I don't get this error on internal master.
> 
> I'm able to use it on HTTPS today. I'm not sure what was the deal with that profile not working at my house. But now it seems fine.

I had some issues as well, related to some Endevor WebServices startup troubles. I think, there was an IPL in our system today, so some services were not respond in the morning, but it is just a guess...

**Comment by katelynienaber** [comment]
> > @nickImbirev There's no errors in the log for the one I took a screenshot of. I checked both consoles. But I still receive the error now. The extension starts successfully, so it's not a big deal. But I don't get this error on internal master.
> > I'm able to use it on HTTPS today. I'm not sure what was the deal with that profile not working at my house. But now it seems fine.
> 
> I had some issues as well, related to some Endevor WebServices startup troubles. I think, there was an IPL in our system today, so some services were not respond in the morning, but it is just a guess...

That's possible for the 2nd error.

For the 1st error, do you have any idea where a property like "name" would be used? If not in a profile then somewhere in the code...

**Comment by nickImbirev** [comment]
> > > @nickImbirev There's no errors in the log for the one I took a screenshot of. I checked both consoles. But I still receive the error now. The extension starts successfully, so it's not a big deal. But I don't get this error on internal master.
> > > I'm able to use it on HTTPS today. I'm not sure what was the deal with that profile not working at my house. But now it seems fine.
> > 
> > 
> > I had some issues as well, related to some Endevor WebServices startup troubles. I think, there was an IPL in our system today, so some services were not respond in the morning, but it is just a guess...
> 
> That's possible for the 2nd error.
> 
> For the 1st error, do you have any idea where a property like "name" would be used? If not in a profile then somewhere in the code...

I mean, this error seems to be from previous a version of E4E (in Vit's fork master branch). We have some breaking changes there and we decided that there will be no backward compatibility. So, we should not have to worry about it. 

The only question I have now, did you test this [branch](https://github.com/VitGottwald/che-che4z-explorer-for-endevor/tree/fix-list-instances) or master in Vit's fork? Because I was able to reproduce the 1st issue only from Vit's master branch.

**Comment by katelynienaber** [comment]
@nickImbirev Ah, there's the problem! Sorry, it seems obvious now :)

I'm satisfied with this. How do you feel about merging it?

**Comment by nickImbirev** [comment]
Thank you @VitGottwald !

**Pull request merged**
